# Generated by Django 5.1.4 on 2026-03-16 02:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('targets', '0002_authcontext'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Friendly label, e.g. 'Security Team Slack'", max_length=100)),
                ('channel_type', models.CharField(choices=[('telegram', 'Telegram Bot'), ('slack', 'Slack Webhook'), ('email', 'Email SMTP')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('telegram_bot_token', models.CharField(blank=True, max_length=200)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=100)),
                ('slack_webhook_url', models.URLField(blank=True, max_length=500)),
                ('smtp_host', models.CharField(blank=True, max_length=200)),
                ('smtp_port', models.PositiveSmallIntegerField(default=587)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_username', models.CharField(blank=True, max_length=200)),
                ('smtp_password', models.CharField(blank=True, max_length=500)),
                ('email_from', models.EmailField(blank=True, max_length=254)),
                ('email_to', models.TextField(blank=True, help_text='Comma-separated recipient email addresses')),
                ('trigger_events', models.JSONField(default=list, help_text='List of TriggerEvent values')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_channels', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_channels', to='targets.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=50)),
                ('payload_preview', models.TextField(blank=True)),
                ('result', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('skip', 'Skipped (inactive)')], default='sent', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notificationchannel')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
