# Generated by Django 5.1.4 on 2026-03-16 02:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthContext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Human label, e.g. 'Admin Role'", max_length=100)),
                ('auth_type', models.CharField(choices=[('none', 'Unauthenticated'), ('bearer', 'Bearer JWT'), ('basic', 'Basic Auth (Base64)'), ('cookie', 'Cookie'), ('api_key', 'API Key')], default='none', max_length=20)),
                ('auth_value', models.TextField(blank=True, help_text='Token / cookie value / base64 basic creds')),
                ('header_name', models.CharField(blank=True, default='Authorization', max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_contexts', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_contexts', to='targets.project')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
