# Generated by Django 5.1.4 on 2026-04-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0005_scanchain_scheduledscan_scandiffreport'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='scandiffreport',
            new_name='scans_scand_module__0309b5_idx',
            old_name='scans_diff_module_project_idx',
        ),
        migrations.AlterField(
            model_name='scanchain',
            name='base_params',
            field=models.JSONField(default=dict, help_text='Fixed params always sent to child (merged with mapped params)'),
        ),
        migrations.AlterField(
            model_name='scanchain',
            name='child_module',
            field=models.CharField(help_text="Module ID to launch downstream, e.g. 'V-01'", max_length=100),
        ),
        migrations.AlterField(
            model_name='scanchain',
            name='param_mapping',
            field=models.JSONField(default=dict, help_text='How to map parent outputs → child params'),
        ),
        migrations.AlterField(
            model_name='scanchain',
            name='parent_module',
            field=models.CharField(db_index=True, help_text="Module ID of the trigger module, e.g. 'R-02'", max_length=100),
        ),
    ]
