# Generated by Django 5.1.4 on 2026-04-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0006_rename_scans_diff_module_project_idx_scans_scand_module__0309b5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanjob',
            name='info_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='low_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='medium_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
