# Generated by Django 5.1.4 on 2026-03-16 02:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('targets', '0002_authcontext'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Penetration Test Report', max_length=300)),
                ('executive_summary', models.TextField(blank=True)),
                ('finding_ids', models.JSONField(blank=True, default=list, help_text='Ordered list of Finding UUIDs to include. Empty = all project findings.')),
                ('logo_base64', models.TextField(blank=True, help_text='Base64 PNG/SVG logo')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('assessor_name', models.CharField(blank=True, max_length=200)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('include_graph_png', models.BooleanField(default=False)),
                ('include_evidence', models.BooleanField(default=True)),
                ('include_remediation', models.BooleanField(default=True)),
                ('min_severity', models.CharField(choices=[('critical', 'Critical only'), ('high', 'High and above'), ('medium', 'Medium and above'), ('low', 'Low and above'), ('info', 'All')], default='info', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('last_format', models.CharField(blank=True, choices=[('html', 'HTML'), ('pdf', 'PDF'), ('json', 'JSON'), ('markdown', 'Markdown')], max_length=20)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='targets.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
