# Generated by Django 5.1.4 on 2026-03-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('targets', '0002_authcontext'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='targets',
            field=models.ManyToManyField(blank=True, help_text='Targets to include in this report. Leave empty to include all project targets.', related_name='reports', to='targets.target'),
        ),
    ]
